worker_processes 4;
daemon off;

error_log stderr;
events { 
    worker_connections 1024; 
}

http {
  charset utf-8;
  log_format access_json '{"logType": "nginx-access", '
                         ' "remoteHost": "$remote_addr", '
                         ' "user": "$remote_user", '
                         ' "time": "$time_local", '
                         ' "request": "$request", '
                         ' "status": $status, '
                         ' "size": $body_bytes_sent, '
                         ' "referer": "$http_referer", '
                         ' "userAgent": "$http_user_agent", '
                         ' "requestTime": $request_time, '
                         ' "httpHost": "$http_host"}';

  access_log /dev/stdout access_json;
  default_type application/octet-stream;
  sendfile on;

  tcp_nopush on;
  keepalive_timeout 30;
  port_in_redirect off;

  resolver {{nameservers}} ipv6=off valid=1s;

  server {
    listen {{ port }};
    server_name localhost;

    allow {{ env "ALLOWED_IP_RANGE" }};
    deny all;

    location / {
        proxy_pass http://clamav-rest-endpoint.apps.internal:8080;
    }
  }
}