worker_processes 4;
daemon off;

error_log stderr;
events { 
    worker_connections 1024; 
}

http {
  charset utf-8;
  log_format access_json '{"logType": "nginx-access", '
                         ' "remoteHost": "$remote_addr", '
                         ' "user": "$remote_user", '
                         ' "time": "$time_local", '
                         ' "request": "$request", '
                         ' "status": $status, '
                         ' "size": $body_bytes_sent, '
                         ' "referer": "$http_referer", '
                         ' "userAgent": "$http_user_agent", '
                         ' "requestTime": $request_time, '
                         ' "httpHost": "$http_host"}';
  access_log /dev/stdout access_json;
  default_type application/octet-stream;
  sendfile on;

  tcp_nopush on;
  keepalive_timeout 30;
  port_in_redirect off;

  resolver {{nameservers}} ipv6=off valid=1s;

  server {
    listen {{ port }};
    server_name localhost;

    allow {{ env "ALLOWED_IP_RANGE" }};
    deny all;

    location / {
        proxy_pass http://clamav-rest-endpoint.apps.internal:8080;
        
        # proxy_http_version 1.1;
        # proxy_set_header Host $cf_forwarded_host;

        # proxy_ssl_server_name on;
        # proxy_ssl_protocols TLSv1.2;
        # proxy_set_header Connection "";
        
        # proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

        # # Use XX-CF-APP-INSTANCE on the original request if you wish to target an instance
        # proxy_set_header X-CF-APP-INSTANCE $http_xx_cf_app_instance;

        # proxy_pass $http_x_forwarded_proto://$http_host$cf_forwarded_uri;

        # # Internal routing is IPv4 only.
        # resolver {{nameservers}} ipv6=off;

        # set $cf_forwarded_host '*';
        # set $cf_forwarded_uri '*';

        # if ($http_x_cf_forwarded_url ~* ^(https?\:\/\/)(.*?)\/(.*)$) {
        #     set $cf_forwarded_host $2;
        #     set $cf_forwarded_uri /$3;
        # }

        # proxy_http_version 1.1;
        # proxy_ssl_server_name on;
        # proxy_ssl_protocols TLSv1.2;
        # proxy_set_header Connection "";
        # proxy_set_header Host $cf_forwarded_host;
        # proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;

        # # Use XX-CF-APP-INSTANCE on the original request if you wish to target an instance
        # proxy_set_header X-CF-APP-INSTANCE $http_xx_cf_app_instance;

        # proxy_pass $http_x_forwarded_proto://$http_host$cf_forwarded_uri;
    }
  }
}