---

# deploy-clamav-rest

jobs:

- name: reconfigure
  serial: true
  plan:
  - get: pipeline-source
    params: {depth: 1}
    trigger: true
  - set_pipeline: self
    file: pipeline-source/ci/pipeline.yml

- name: dev
  plan:
  - in_parallel:
    - get: clamav-rest-image
      params: {skip_download: true}
      trigger: true
    - get: general-task
    - get: source
      params: {depth: 1}
      trigger: true
  - task: deploy
    image: general-task
    file: source/ci/deploy.yml
    params:
      CF_API: ((dev-cf-api-url))
      CF_DOCKER_PASSWORD: ((ecr_aws_secret))
      CF_DOCKER_USERNAME: ((ecr_aws_key))
      CF_ORG: cloud-gov
      CF_PASSWORD: ((dev-cf-password))
      CF_SPACE: acceptance-tests
      CF_USERNAME: ((dev-cf-username))
      CLAMAV_REST_DOMAIN: apps.internal
      CLAMAV_REST_HOSTNAME: clamav-rest-acceptance
  - task: test
    image: general-task
    file: source/ci/test.yml
    params:
      CF_API: ((dev-cf-api-url))
      CF_ORG: cloud-gov
      CF_PASSWORD: ((dev-cf-password))
      CF_SPACE: acceptance-tests
      CF_USERNAME: ((dev-cf-username))
      CLAMAV_REST_DOMAIN: apps.internal
      CLAMAV_REST_HOSTNAME: clamav-rest-acceptance

resources:

- name: clamav-rest-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: clamav-rest
    aws_region: us-gov-west-1
    tag: latest

- name: general-task
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: general-task
    aws_region: us-gov-west-1
    tag: latest

- name: pipeline-source
  type: git
  icon: github-circle
  check_every: 10s
  source:
    branch: develop
    commit_verification_keys: ((cloud-gov-pgp-keys))
    paths: [ci/pipeline.yml]
    uri: https://github.com/cloud-gov/clamav-rest-image.git

- name: source
  type: git
  icon: github-circle
  check_every: 10s
  source:
    branch: develop
    commit_verification_keys: ((cloud-gov-pgp-keys))
    ignore_paths: [ci/pipeline.yml]
    uri: https://github.com/cloud-gov/clamav-rest-image.git

resource_types:

- name: git
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: git-resource
    aws_region: us-gov-west-1
    tag: latest

- name: registry-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: registry-image-resource
    aws_region: us-gov-west-1
    tag: latest