---

# deploy-clamav-rest

jobs:

- name: reconfigure
  serial: true
  plan:
  - get: pipeline-source
    params: {depth: 1}
    trigger: true
  - set_pipeline: self
    file: pipeline-source/ci/pipeline.yml

- name: dev
  plan:
  - in_parallel:
    - get: clamav-rest-image
      trigger: true
    - get: source
      params: {depth: 1}
      trigger: true
  - in_parallel:
    - put: cf-dev
      params:
        docker_password: ((ecr_aws_secret))
        docker_username: ((ecr_aws_key))
        manifest: source/cf/manifest.yml
        show_app_log: true
  
  # on_failure:
  #   put: slack
  #   params:
  #     <<: *slack-failure-params
  #     text: |
  #       :x: FAILED to deploy external-domain-broker on development
  #       <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>



resources:

- name: cf-dev
  type: cf
  icon: cloud-upload
  source:
    api: ((dev-cf-api-url))
    username: ((dev-cf-username))
    password: ((dev-cf-password))
    organization: ((cloud-gov))
    space: ((acceptance-tests))

- name: clamav-rest-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: clamav-rest
    aws_region: us-gov-west-1
    tag: latest

- name: pipeline-source
  type: git
  icon: github-circle
  check_every: 10s
  source:
    branch: develop
    commit_verification_keys: ((cloud-gov-pgp-keys))
    paths: [ci/pipeline.yml]
    uri: https://github.com/cloud-gov/clamav-rest-image.git

- name: source
  type: git
  icon: github-circle
  check_every: 10s
  source:
    branch: develop
    commit_verification_keys: ((cloud-gov-pgp-keys))
    ignore_paths: [ci/pipeline.yml]
    uri: https://github.com/cloud-gov/clamav-rest-image.git

resource_types:

- name: cf
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: cf-resource
    aws_region: us-gov-west-1
    tag: latest

- name: git
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: git-resource
    aws_region: us-gov-west-1
    tag: latest

- name: registry-image
  type: registry-image
  source:
    aws_access_key_id: ((ecr_aws_key))
    aws_secret_access_key: ((ecr_aws_secret))
    repository: registry-image-resource
    aws_region: us-gov-west-1
    tag: latest